# Generated by Django 6.0.5 on 2026-06-05 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_classgrade_studentprofile_face_embedding_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="registration_date",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="face_id_image",
            field=models.ImageField(blank=True, null=True, upload_to="face_profiles/"),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="program_track",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="staffprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="studentprofile",
            table=None,
        ),
    ]
